[package]
name = "stm32-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.6"
stm32f4xx-hal = { version = "0.10", features = ["rt", "stm32f411"] }
panic-halt = "0.2.0"
